
- name: Uninstall nodejs
  become: yes
  yum:
    name: nodejs
    state: absent

- name: Install Node 7.* repo
  become: yes
  yum_repository:
    name: nodejs-rpm
    description: Node epel yum repo
    baseurl: "{{base_url}}"
    gpgcheck: no

- name: Install nodejs
  become: yes
  yum:
    name: "nodejs-{{version}}"
    state: latest