---
#- name: Uninstall nodejs
#  become: yes
#  yum_repository:
#    name: nodejs-rpm
#    state: absent
#  notify: yum-clean-metadata

- name: Uninstall node
  become: yes
  yum:
    name: nodejs
    state: absent

- name: Installing Node repo
  become: yes
  yum_repository:
    name: nodejs
    description: Node epel yum repo
    baseurl: "{{node_repo}}"
    gpgcheck: no

- name: Install nodejs {{node_version}}
  become: yes
  yum:
    name: "nodejs-{{node_version}}"
    state: latest