---
- hosts: webserver1
  vars_files:
    - ./configs/webserver1_config.yml
  roles:
    - nginx
    - nodejs

- hosts: webserver2
  vars_files:
    - ./configs/webserver2_config.yml
  roles:
    - nodejs
