---
- hosts: myhosts
  vars_files:
    - config.yml
  roles:
    - nginx
    - nodejs
  vars:
    version: "{{node_7_9_version}}"

- hosts: another-host
  vars_files:
    - config.yml
  roles:
    - nodejs
  vars:
    version: "{{node_7_10_version}}"
