---
- hosts: webserver1
  vars_files:
    - ./configs/webserver1_config.yml
  roles:
    - webserver1

- hosts: webserver2
  vars_files:
    - ./configs/webserver2_config.yml
  roles:
    - webserver2
